image: docker:19-git
services:
  - name: docker:19-dind
    command: [ "--tls=false", "--registry-mirror", "http://10.96.77.230" ]
variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOCKER_TLS_CERTDIR: ""
  KUBECONFIG: /etc/deploy/config
  CONTAINER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  HELM_NAME: book-manager-charts
  HELM_VERSION: v0.0.6

before_script:
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

mvnBuild:
  stage: build
  script:
    - docker build --network=host -t "$CONTAINER_TAG" .
    - docker push "$CONTAINER_TAG"
  only:
    - branches

deploy_staging:
  image: lwolf/helm-kubectl-docker:v1.20.5-v3.5.3
  stage: deploy
  before_script:
    - mkdir -p /etc/deploy
    - echo ${kube_config} | base64 -d > ${KUBECONFIG}
    - echo ${values_file} | base64 -d > /etc/deploy/values.yaml
    - export HELM_EXPERIMENTAL_OCI=1
    - helm repo add minthe https://registry.minthe.net/michael/$HELM_NAME
    - helm registry login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" registry.minthe.net
    - helm chart pull registry.minthe.net/michael/$HELM_NAME:$HELM_VERSION
  script:
    - cd /etc/deploy
    - helm chart export registry.minthe.net/michael/$HELM_NAME:$HELM_VERSION
    - helm upgrade -n bkmgr-development -f values.yaml book-manager ./book-manager/ --set=image.tag=$CI_COMMIT_SHORT_SHA
  environment:
    name: staging
    url: https://book-dev.minthe.net
    kubernetes:
      namespace: bkmgr-dev