image: docker:19-git
services:
  - name: docker:19-dind
    command: [ "--tls=false" ]
variables:
  DOCKER_DRIVER: overlay
  DOCKER_HOST: tcp://127.0.0.1:2375
  DOCKER_TLS_CERTDIR: ""
  CONTAINER_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

before_script:
  - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"

mvnBuild:
  stage: build
  script:
    - docker build --network=host -t "$CONTAINER_TAG" .
    - docker push "$CONTAINER_TAG"
  only:
    - branches